name: Build Zoo Notes PR branch

on:
  # Run this workflow on changes to any PR.
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3

    - name: Node.js build
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/hydrogen'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn build
      env:
        REACT_APP_ENV: production

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ./build/commit_id.txt
